// End-to-end audit against real endpoints and isolated persisted data.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { spawn } = require('node:child_process');
const root = path.resolve(__dirname, '..');
const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'usb-showcase-'));
const python = process.env.SHOWCASE_PYTHON;
const base = 'http://127.0.0.1:8001';
let server, browser, log = '', checks = 0;
const errors = [];
function ok(value, message) { assert.ok(value, message); checks++; }
const source = {'attendance.csv':'name,present\nAyesha,yes\n','config.json':'{"safe":true}\n','image.png':Buffer.from([137,80,78,71,13,10,26,10,1,2,3]),'nested/lab_record.bin':Buffer.from([0,1,2,255,3]),'notes.txt':'project notes\n'};
function folder(name, entries) { const dir=path.join(temp,name); for(const [file,data] of Object.entries(entries)){fs.mkdirSync(path.dirname(path.join(dir,file)),{recursive:true});fs.writeFileSync(path.join(dir,file),data);} return dir; }
const original = folder('original_files', source);
const variants={clean:{...source},corrupted:{...source,'attendance.csv':'changed attendance'},missing:{...source},extra:{...source,'extra_file.txt':'extra'},mixed:{...source,'notes.txt':'changed','extra_file.txt':'extra'}};
delete variants.missing['image.png']; delete variants.mixed['image.png'];
const dirs=Object.fromEntries(Object.entries(variants).map(([k,v])=>[k,folder('backup_'+k,v)]));
const totals={clean:[5,0,0,0],corrupted:[4,1,0,0],missing:[4,0,1,0],extra:[5,0,0,1],mixed:[3,1,1,1]};
async function start(){server=spawn(python,[path.join(__dirname,'showcase_server.py')],{cwd:root,env:{...process.env,SHOWCASE_DATA:temp},windowsHide:true});server.stdout.on('data',b=>log+=b);server.stderr.on('data',b=>log+=b); for(let n=0;n<80;n++){try{if((await fetch(base+'/api/health')).ok)return;}catch{}await new Promise(r=>setTimeout(r,100));}throw new Error('Server failed: '+log);}
async function stop(){if(server && server.exitCode===null){const done=new Promise(r=>server.once('exit',r));server.kill();await done;}}
async function selectNativeFolder(page,kind,name){
 const prepared=await fetch(base+'/__test/folder/'+encodeURIComponent(name),{method:'POST'});assert.equal(prepared.status,200);
 const response=page.waitForResponse(r=>r.url().endsWith('/api/folders/select')&&r.request().method()==='POST');await page.locator('#select-'+kind+'-button').click();assert.equal((await response).status(),200);await page.waitForFunction(({kind,name})=>document.querySelector('#'+kind+'-folder-name').textContent===name,{kind,name});
}
async function selectNativeLabFolder(page,name){
 const prepared=await fetch(base+'/__test/folder/'+encodeURIComponent(name),{method:'POST'});assert.equal(prepared.status,200);
 const response=page.waitForResponse(r=>r.url().endsWith('/api/folders/select')&&r.request().method()==='POST');await page.locator('#lab-select-backup-button').click();assert.equal((await response).status(),200);await page.waitForFunction(name=>document.querySelector('#lab-backup-name').textContent===name,name);
}
async function choose(page,prefix,label){await page.locator('#'+prefix+'-trigger').click();await page.locator('#'+prefix+'-listbox [role="option"]').filter({hasText:label}).click();}
async function counts(page,prefix){return Promise.all(['verified','corrupted','missing','extra'].map(s=>page.locator('#'+prefix+s+(prefix==='summary-'?'-count':'')).innerText())).then(a=>a.map(Number));}
async function run(page,selector,endpoint){const response=page.waitForResponse(r=>r.url().endsWith(endpoint)&&r.request().method()==='POST');await page.locator(selector).click();const r=await response;assert.equal(r.status(),200);await page.waitForFunction(()=>!document.querySelector('button[aria-busy="true"]'),null,{timeout:15000});return r.json();}
async function modalCancel(page,prefix){for(const mode of ['cancel','escape','backdrop']){await page.locator(prefix==='reference-replace'?'#generate-reference-button':'#history-clear-button').click();await page.locator('#'+prefix+'-cancel').waitFor({state:'visible'});ok(await page.locator('#'+prefix+'-cancel').evaluate(e=>e===document.activeElement),'initial cancel focus');await page.locator('#'+prefix+'-cancel').press('Shift+Tab');ok(await page.locator('#'+prefix+'-confirm').evaluate(e=>e===document.activeElement),'focus trap');if(mode==='cancel')await page.locator('#'+prefix+'-cancel').click();if(mode==='escape')await page.locator('#'+prefix+'-confirm').press('Escape');if(mode==='backdrop')await page.locator('#'+prefix+'-dialog').click({position:{x:3,y:3}});ok(await page.locator('#'+prefix+'-dialog').isHidden(),'cancel closes');}}
async function visual(page,name){for(const [width,height] of [[1920,1080],[1600,900],[1366,768]]){await page.setViewportSize({width,height});await page.evaluate(()=>window.scrollTo(0,0));const result=await page.evaluate(()=>({overflow:document.scrollingElement.scrollWidth>innerWidth,nav:getComputedStyle(document.querySelector('.sidebar')).position,visibleNative:[...document.querySelectorAll('select')].filter(e=>e.getClientRects().length && getComputedStyle(e).visibility!=='hidden').length}));ok(!result.overflow,name+' overflow');ok(result.visibleNative===0,name+' native select');await page.screenshot({path:path.join(temp,name+'-'+width+'.png'),fullPage:true});}}
async function pickerAudit(page,prefix){
 for(const [width,height] of [[1920,1080],[1600,900],[1366,768]]){
  await page.setViewportSize({width,height});const trigger=page.locator('#'+prefix+'-trigger');await trigger.scrollIntoViewIfNeeded();await trigger.press('Enter');ok(await trigger.getAttribute('aria-expanded')==='true','picker opens');await trigger.press('End');ok(Boolean(await trigger.getAttribute('aria-activedescendant')),'active descendant');
  const geometry=await page.evaluate(prefix=>{const t=document.querySelector('#'+prefix+'-trigger').getBoundingClientRect(),l=document.querySelector('#'+prefix+'-listbox').getBoundingClientRect();return {width:Math.abs(t.width-l.width),contained:l.left>=0&&l.right<=innerWidth+1&&l.top>=0&&l.bottom<=innerHeight+1,gap:Math.min(Math.abs(l.top-t.bottom-6),Math.abs(t.top-l.bottom-6))};},prefix);
  ok(geometry.width<1&&geometry.contained&&geometry.gap<2,'picker viewport geometry '+prefix);await page.screenshot({path:path.join(temp,prefix+'-open-'+width+'.png')});await trigger.press('Home');await trigger.press('Escape');ok(await trigger.getAttribute('aria-expanded')==='false','escape');await trigger.press('Space');await trigger.press('ArrowDown');await trigger.press('Enter');await trigger.press('Enter');await trigger.press('Tab');ok(await trigger.getAttribute('aria-expanded')==='false','tab close');await trigger.click();await page.locator('#topbar-page-title').click();ok(await trigger.getAttribute('aria-expanded')==='false','outside close');
 }
}
async function main(){
 await start(); browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});const page=await browser.newPage({viewport:{width:1366,height:768}});page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.goto(base);await page.waitForLoadState('networkidle');
 await page.evaluate(()=>{window.showDirectoryPicker=()=>{throw new Error('browser picker must not run');};});ok(await page.locator('input[type="file"]').count()===0,'no browser file inputs anywhere in application');
 ok(await page.locator('#generate-reference-button').isDisabled(),'fresh generate disabled');ok(await page.locator('#verify-backup-button').isDisabled(),'fresh verify disabled');
 await selectNativeFolder(page,'source','original_files');await run(page,'#generate-reference-button','/api/reference/generate-selected');await page.waitForFunction(()=>document.querySelector('#source-reference-status').textContent==='Ready');
 const reference=await (await fetch(base+'/api/reference/current')).json();ok(reference.file_count===5,'reference count');
 const records=[];
 for(const [name,dir] of Object.entries(dirs)){
  await selectNativeFolder(page,'backup','backup_'+name);const result=await run(page,'#verify-backup-button','/api/verification/run-selected');records.push(result);await page.waitForFunction(()=>document.querySelector('#verify-backup-label').textContent==='Verify Again');assert.deepEqual(await counts(page,'summary-'),totals[name]);checks++;ok(result.results.some(r=>r.relative_path==='nested/lab_record.bin'&&r.status==='verified'),'nested');
  for(const row of result.results){if(row.status==='verified')assert.equal(row.source_crc32,row.backup_crc32);if(row.status==='corrupted')assert.notEqual(row.source_crc32,row.backup_crc32);if(row.status==='missing')assert.equal(row.backup_crc32,null);if(row.status==='extra')assert.equal(row.source_crc32,null);}
  for(const [i,label] of ['All Files','Verified','Corrupted','Missing','Extra'].entries()){await choose(page,'results-filter',label);const expected=i===0?result.results.length:totals[name][i-1];assert.equal(await page.locator('#verification-results-body tr .result-badge').count(),expected);assert.deepEqual(await counts(page,'summary-'),totals[name]);if(!expected)ok((await page.locator('#verification-results-body').innerText()).includes('No matching files'),'filter empty');checks++;}
  const csv=await fetch(base+'/api/history/'+result.history_record_id+'/csv');const data=Buffer.from(await csv.arrayBuffer());ok(data.subarray(0,3).equals(Buffer.from([239,187,191])),'BOM');const text=data.toString('utf8');ok(text.includes('Verification ID')&&text.includes('nested/lab_record.bin'),'CSV full');ok(text.split('\r\n').filter(l=>/^(Verified|Corrupted|Missing|Extra),[^\d]/.test(l)).length===result.results.length,'CSV complete rows');
  console.log(name,totals[name]);
 }
 await choose(page,'results-filter','All Files');await visual(page,'verification');await pickerAudit(page,'results-filter');
 const beforeCancel=await page.locator('#backup-folder-name').innerText();await fetch(base+'/__test/folder/__cancel__',{method:'POST'});const cancelResponse=page.waitForResponse(r=>r.url().endsWith('/api/folders/select'));await page.locator('#select-backup-button').click();await cancelResponse;ok(await page.locator('#backup-folder-name').innerText()===beforeCancel,'native cancel preserves selection');
 await selectNativeFolder(page,'source','original_files');ok(await page.locator('#summary-state-label').innerText()==='NO CURRENT RESULT','source invalidates');ok(await page.locator('#source-reference-status').innerText()==='Not created','same-name selection not falsely Ready');await modalCancel(page,'reference-replace');assert.deepEqual(await (await fetch(base+'/api/reference/current')).json(),reference);checks++;
 await page.locator('#generate-reference-button').click();await run(page,'#reference-replace-confirm','/api/reference/generate-selected');ok((await (await fetch(base+'/api/history')).json()).count===5,'replace preserves history');await page.locator('#clear-selection-button').click();ok(await page.locator('#verify-backup-button').isDisabled(),'clear verify');ok(await page.locator('#generate-reference-button').isDisabled(),'clear replace');ok(await page.locator('#source-reference-status').innerText()==='Ready','clear reference');
 await page.getByRole('link',{name:'Error Lab',exact:true}).click();await selectNativeLabFolder(page,'backup_clean');
 for(const [method,target,expected,total] of [['modify-byte','image.png','Corrupted',[4,1,0,0]],['append-data','notes.txt','Corrupted',[4,1,0,0]],['truncate-file','config.json','Corrupted',[4,1,0,0]],['remove-file','nested/lab_record.bin','Missing',[4,0,1,0]],['add-extra',null,'Extra',[5,0,0,1]]]){
  await page.locator('input[value="'+method+'"]').check();ok(await page.locator('#lab-result-panel').isHidden(),'method invalidates');if(target){ok(await page.locator('#lab-run-button').isDisabled(),'target required');await choose(page,'lab-target',target);}else{ok(await page.locator('#lab-target-control').isHidden(),'M5 hidden picker');ok(await page.locator('#lab-target-info').evaluate(e=>e.tagName==='DIV'&&e.tabIndex===-1&&!e.isContentEditable),'M5 info');}
 await run(page,'#lab-run-button','/api/error-lab/run-selected');await page.waitForFunction(()=>document.querySelector('#lab-run-label').textContent==='Run Again');assert.equal(await page.locator('#lab-result-actual').innerText(),expected);assert.deepEqual(await counts(page,'lab-summary-'),total);const crc=await page.locator('#lab-backup-crc').innerText();await run(page,'#lab-run-button','/api/error-lab/run-selected');await page.waitForFunction(()=>document.querySelector('#lab-run-label').textContent==='Run Again');assert.equal(await page.locator('#lab-backup-crc').innerText(),crc);checks+=3;console.log(method,expected,total);
 }
 const labStateBeforeCancel=await page.evaluate(()=>({name:document.querySelector('#lab-backup-name').textContent,result:document.querySelector('#lab-result-actual').textContent,method:document.querySelector('input[name="lab-simulation"]:checked').value}));await fetch(base+'/__test/folder/__cancel__',{method:'POST'});const labCancelResponse=page.waitForResponse(r=>r.url().endsWith('/api/folders/select'));await page.locator('#lab-select-backup-button').click();await labCancelResponse;assert.deepEqual(await page.evaluate(()=>({name:document.querySelector('#lab-backup-name').textContent,result:document.querySelector('#lab-result-actual').textContent,method:document.querySelector('input[name="lab-simulation"]:checked').value})),labStateBeforeCancel);checks++;
 await visual(page,'error-lab');await page.locator('input[value="modify-byte"]').check();await pickerAudit(page,'lab-target');await page.locator('#lab-reset-button').click();ok(await page.locator('#lab-run-button').isDisabled(),'reset lab');ok((await (await fetch(base+'/api/history')).json()).count===5,'lab no history');for(const [file,bytes] of Object.entries(source))assert.deepEqual(fs.readFileSync(path.join(dirs.clean,file)),Buffer.from(bytes));checks++;
 await page.getByRole('link',{name:'History',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.history-item').length===5);assert.equal(await page.locator('#history-clean-count').innerText(),'1');assert.equal(await page.locator('#history-issues-count').innerText(),'4');
 await page.locator('#history-search-input').fill('BACKUP_MIXED');ok(await page.locator('.history-item').count()===1,'case insensitive search');await choose(page,'history-status','Clean');ok(await page.locator('.history-item').count()===0,'combined empty');await choose(page,'history-status','Issues');ok(await page.locator('.history-item').count()===1,'combined issues');await choose(page,'history-sort','Oldest first');await page.locator('.history-item button').click();await page.locator('#history-detail-panel').waitFor({state:'visible'});await choose(page,'history-results','Missing');ok(await page.locator('#history-results-count').innerText()==='1 of 6 files','detail count');await page.locator('#history-detail-close').click();ok(await page.locator('.history-item button').evaluate(e=>e===document.activeElement),'details restores focus');ok(await page.locator('#history-search-input').inputValue()==='BACKUP_MIXED','details search');await page.locator('#history-search-input').fill('');await choose(page,'history-status','All');await visual(page,'history');await modalCancel(page,'history-clear');
 await pickerAudit(page,'history-status');await pickerAudit(page,'history-sort');await choose(page,'history-status','All');await page.locator('.history-item button').first().click();await page.locator('#history-detail-panel').waitFor({state:'visible'});await pickerAudit(page,'history-results');await visual(page,'history-details');await page.locator('#history-detail-close').click();
 await page.getByRole('link',{name:'Error Lab',exact:true}).click();for(const file of ['error_lab_method_states.mjs','error_lab_post_run_states.mjs','target_picker_states.mjs']){const module=await import(require('node:url').pathToFileURL(path.join(__dirname,file)));const result=await module.default({playwright:page,reload:async()=>{await page.reload();await page.waitForLoadState('networkidle');},selectBackup:async()=>selectNativeLabFolder(page,'backup_clean')},dirs.clean);console.log(file,result.passed);checks+=result.passed;}
 const before=await (await fetch(base+'/api/history')).json();await stop();await start();await page.reload();await page.waitForLoadState('networkidle');assert.deepEqual(await (await fetch(base+'/api/history')).json(),before);ok((await (await fetch(base+'/api/reference/current')).json()).exists,'restart persistence');
 await page.getByRole('link',{name:'About',exact:true}).click();await visual(page,'about');
 const chrome=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});const chromePage=await chrome.newPage();chromePage.on('pageerror',e=>errors.push('Chrome: '+String(e)));await chromePage.goto(base);await chromePage.waitForLoadState('networkidle');await chromePage.evaluate(()=>{window.showDirectoryPicker=()=>{throw new Error('browser picker must not run');};});await selectNativeFolder(chromePage,'source','original_files');await selectNativeFolder(chromePage,'backup','backup_clean');await chromePage.getByRole('link',{name:'Error Lab',exact:true}).click();await selectNativeLabFolder(chromePage,'backup_clean');ok(await chromePage.locator('#lab-backup-name').innerText()==='backup_clean','Chrome all folder controls use backend-native picker');await chrome.close();
 for(const [width,height] of [[1920,1080],[1600,900],[1366,768]]){
  for(let i=0;i<21;i++){const form=new FormData();form.append('backup_name','backup_clean');form.append('record_history','true');for(const [file,bytes] of Object.entries(source)){form.append('files',new Blob([bytes]),path.basename(file));form.append('relative_paths','backup_clean/'+file);}ok((await fetch(base+'/api/verification/run',{method:'POST',body:form})).ok,'history seed');}
  await page.setViewportSize({width,height});await page.goto(base+'/#history');await page.reload();await page.waitForLoadState('networkidle');await page.waitForFunction(()=>document.querySelectorAll('.history-item').length>=21);await page.mouse.move(width-100,height/2);await page.mouse.wheel(0,1800);await page.waitForTimeout(300);const deep=await page.evaluate(()=>document.scrollingElement.scrollTop);ok(deep>200,'true scroll owner moves');await page.locator('#history-clear-button').evaluate(e=>e.focus({preventScroll:true}));await page.locator('#history-clear-button').press('Enter');await page.locator('#history-clear-cancel').press('Escape');ok(await page.evaluate(()=>document.scrollingElement.scrollTop)===deep,'cancel preserves deep scroll');
  await page.locator('#history-clear-button').press('Enter');await page.screenshot({path:path.join(temp,'clear-dialog-'+width+'.png')});await page.locator('#history-clear-confirm').click();await page.waitForFunction(()=>document.querySelector('#history-total-count').textContent==='0'&&document.scrollingElement.scrollTop===0);ok(await page.locator('#history-clear-button').isDisabled(),'clear disabled');ok((await (await fetch(base+'/api/reference/current')).json()).exists,'clear preserves ref');await page.screenshot({path:path.join(temp,'clear-result-'+width+'.png')});
 }
 ok(errors.length===0,'browser errors '+errors);ok(!/Traceback|Exception in ASGI/.test(log),'server tracebacks');console.log(JSON.stringify({checks,errors,artifacts:temp}));
}
main().catch(e=>{console.error(e);process.exitCode=1;console.log('artifacts',temp);}).finally(async()=>{if(browser)await browser.close();await stop();});
